### ISSUE TITLE
Role Mapping issue

### ISSUE THREAD

**Issue by S1Josh** [expresstechsoftware/connect-discord-tutor-lms#34]
Within the discord settings we are able to assign roles to certain courses and the role will be given to the student upon completion of the course.

However within the settings when we we pair up the role with the desired course and then click save changes all of the previous role mappings that were already in place get removed, whilst this isn't the hugest issue and we sort out by adding the roles again it does become tedious when we have a large number of roles to assign to a large number of courses

**Comment by younes-dro** [comment]
@ravisoni6262  @S1Josh

I tested with the lastest version of the Add-on available for download :



https://github.com/expresstechsoftware/connect-discord-tutor-lms/assets/31171/747f21e4-49c9-4236-be65-898be10b1ec2
